DROP POLICY IF EXISTS profiles_public_read ON public.profiles;
DROP POLICY IF EXISTS profiles_own_insert ON public.profiles;
DROP POLICY IF EXISTS profiles_own_update ON public.profiles;
DROP POLICY IF EXISTS posts_public_read ON public.posts;
DROP POLICY IF EXISTS posts_own_insert ON public.posts;
DROP POLICY IF EXISTS posts_own_update ON public.posts;
DROP POLICY IF EXISTS posts_own_delete ON public.posts;
DROP POLICY IF EXISTS post_likes_public_read ON public.post_likes;
DROP POLICY IF EXISTS post_likes_own_insert ON public.post_likes;
DROP POLICY IF EXISTS post_likes_own_delete ON public.post_likes;
DROP POLICY IF EXISTS vip_posts_vip_read ON public.vip_posts;
DROP POLICY IF EXISTS vip_posts_vip_insert ON public.vip_posts;
DROP POLICY IF EXISTS vip_posts_own_update ON public.vip_posts;
DROP POLICY IF EXISTS vip_posts_own_delete ON public.vip_posts;
DROP POLICY IF EXISTS vip_post_likes_vip_read ON public.vip_post_likes;
DROP POLICY IF EXISTS vip_post_likes_vip_insert ON public.vip_post_likes;
DROP POLICY IF EXISTS vip_post_likes_own_delete ON public.vip_post_likes;
DROP POLICY IF EXISTS subscriptions_own_read ON public.subscriptions;
DROP POLICY IF EXISTS notifications_own_read ON public.notifications;
DROP POLICY IF EXISTS notifications_own_update ON public.notifications;

create policy "profiles_public_read" on public.profiles for select to authenticated using (true);
create policy "profiles_own_insert" on public.profiles for insert to authenticated with check (id = auth.uid());
create policy "profiles_own_update" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "posts_public_read" on public.posts for select to authenticated using (true);
create policy "posts_own_insert" on public.posts for insert to authenticated with check (author_id = auth.uid());
create policy "posts_own_update" on public.posts for update to authenticated using (author_id = auth.uid()) with check (author_id = auth.uid());
create policy "posts_own_delete" on public.posts for delete to authenticated using (author_id = auth.uid());
create policy "post_likes_public_read" on public.post_likes for select to authenticated using (true);
create policy "post_likes_own_insert" on public.post_likes for insert to authenticated with check (user_id = auth.uid());
create policy "post_likes_own_delete" on public.post_likes for delete to authenticated using (user_id = auth.uid());
create policy "vip_posts_vip_read" on public.vip_posts for select to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_vip = true and (p.vip_expires_at is null or p.vip_expires_at > now())));
create policy "vip_posts_vip_insert" on public.vip_posts for insert to authenticated with check (author_id = auth.uid() and exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_vip = true and (p.vip_expires_at is null or p.vip_expires_at > now())));
create policy "vip_posts_own_update" on public.vip_posts for update to authenticated using (author_id = auth.uid()) with check (author_id = auth.uid());
create policy "vip_posts_own_delete" on public.vip_posts for delete to authenticated using (author_id = auth.uid());
create policy "vip_post_likes_vip_read" on public.vip_post_likes for select to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_vip = true and (p.vip_expires_at is null or p.vip_expires_at > now())));
create policy "vip_post_likes_vip_insert" on public.vip_post_likes for insert to authenticated with check (user_id = auth.uid() and exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_vip = true and (p.vip_expires_at is null or p.vip_expires_at > now())));
create policy "vip_post_likes_own_delete" on public.vip_post_likes for delete to authenticated using (user_id = auth.uid());
create policy "subscriptions_own_read" on public.subscriptions for select to authenticated using (user_id = auth.uid());
create policy "notifications_own_read" on public.notifications for select to authenticated using (user_id = auth.uid());
create policy "notifications_own_update" on public.notifications for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
